apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-mysql
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.app }}
data:
  init.sql:
    {{ .Values.database.initSQL | nindent 4 }}
