apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-mysql-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{-  range $k, $v:= .Values.secrets }}
    {{ $k }}: {{ $v | quote }}
  {{- end }}