apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-pv-data
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ .Values.pv_storage }}
  hostPath:
    path: /data/
