apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-app-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- range $k, $v:= .Values.data }}
    {{ $k }}: {{ $v | quote}}
  {{- end }}