# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-mysql
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.labels.app }}
  ports:
  - name: mysql
    port: 3306
  clusterIP: None

# helm-sql-mysql-0.helm-sql-mysql.mysql.svc.cluster.local
# pod-name.service-name.namespace.svc.cluster.local
# pod-name.service-name
# mysql-0.mysql.mysql.svc.cluster.local