# myhelm - dployment
global:
  chartName: myhelm
namespace: todoapp

data:
  SECRET_KEY: QGUyKHl4KXYmdGdoM19zPTB5amEtaSFkcGVieHN6XmRnNDd4KS1rJmtxXzN6Zio5ZSoK
  DB_NAME: "YXBwX2RiCg=="
  DB_USER: "YXBwX3VzZXI="
  DB_PASSWORD: "MTIzNA=="
  DB_HOST: "bXlzcWwtMC5teXNxbC5teXNxbC5zdmMuY2x1c3Rlci5sb2NhbA=="

env:
  - name: PYTHONUNBUFFERED
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: PYTHONUNBUFFERED
  - name: SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: app-secret
        key: SECRET_KEY
  - name: DB_NAME
    valueFrom:
      secretKeyRef:
        name: app-secret
        key: DB_NAME
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: app-secret
        key: DB_USER
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: app-secret
        key: DB_PASSWORD
  - name: DB_HOST
    valueFrom:
      secretKeyRef:
        name: app-secret
        key: DB_HOST

resources:
  requests:
    memory: "256Mi"
    cpu: "300m"
  limits:
    memory: "256Mi"
    cpu: "600m"

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

containers:
  image: ikulyk404/todoapp
  tag: 4.0.1

affinity:
  weight: 1
  key: app
  values: kube2py

minReplicas: 2
maxReplicas: 5

cpuAverageUtilization: 70
memoryAverageUtilization: 70

pv_storage: 1Gi
pvc_storage: 1Gi

rbac:
  namespace: todoapp
  rules:
    apiGroups: '[""]'
    resources: '["secrets"]'
    verbs: '["get", "watch", "list"]'
