apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: todoapp
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todoapp
  minReplicas: {{ .Values.minReplicas }}
  maxReplicas: {{.Values.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.cpuAverageUtilization }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.memoryAverageUtilization }}
