apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}-secrets-reader
  namespace: {{ .Values.rbac.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Chart.Name }}-secrets-role
  namespace: {{ .Values.rbac.namespace }}
rules:
- apiGroups: {{ .Values.rbac.rules.apiGroups }}
  resources: {{ .Values.rbac.rules.resources }}
  verbs: {{ .Values.rbac.rules.verbs }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}-secrets-reader-binding
  namespace: {{ .Values.rbac.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Chart.Name }}-secrets-reader
  namespace: {{ .Values.rbac.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Chart.Name }}-secrets-role
